# Generated by Django 5.2 on 2025-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-pesa'), ('bank', 'Bank'), ('cash', 'Cash')], default='mpesa', max_length=7),
        ),
    ]
